name: PR Comment

on:
  pull_request_target:
    types:
      - opened
    paths:
    - '**.json'

jobs:
  PR-Comment:
    if: github.actor != 'kingthorin' && github.actor != 'vwadbot' && github.actor != 'psiinon' && github.actor != 'raulsiles'  
    runs-on: ubuntu-latest
    steps:
    - name: PR Comment
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: ${{ github.event.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ':warning: Did you follow the [contribution guidance](https://github.com/OWASP/www-project-vulnerable-web-applications-directory#contributions)? PRs adding or updating apps should generally be made against the [source repo `OWASP/OWASP-VWAD`](https://github.com/OWASP/OWASP-VWAD).'
          })
